/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parking;

import com.sun.glass.events.KeyEvent;
import java.awt.*;
import java.sql.*;
import javax.swing.*;

public class UiLogin extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public UiLogin() {
        initComponents();
        jPanel4.setFocusable(true);
        setLocationRelativeTo(null);
    }

    public void login(){
        String sql = "select * from adminandstaffdata where user=? and pass=?";
        try {
            con = MyConnection.getConnection();
            pst = con.prepareStatement(sql);
            pst.setString(1, user.getText());
            pst.setString(2, pass.getText());
            rs = pst.executeQuery();
            if (rs.next()) {
                if (rs.getString("rank").equals("admin")) {
                    MainUser mainUser = new MainUser(user.getText(), "admin");
                    mainUser.setVisible(true);
                    mainUser.pack();
                    mainUser.setLocationRelativeTo(null);
                    mainUser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                } else {
                    MainUser mainUser = new MainUser(user.getText(), "not");
                    mainUser.setVisible(true);
                    mainUser.pack();
                    mainUser.setLocationRelativeTo(null);
                    mainUser.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect username or password");
            }
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        pass = new javax.swing.JPasswordField();
        button1 = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exitLable = new javax.swing.JLabel();
        bn_setupdata = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parking System");
        setBackground(new java.awt.Color(102, 102, 102));
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setForeground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(35, 43, 43));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 254));
        jLabel1.setText("Username");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 23));

        user.setBackground(new java.awt.Color(35, 43, 43));
        user.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        user.setForeground(new java.awt.Color(254, 255, 255));
        user.setText("username");
        user.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        user.setCaretColor(new java.awt.Color(254, 255, 255));
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel5.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 371, 36));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 371, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 371, 10));

        pass.setBackground(new java.awt.Color(35, 43, 43));
        pass.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        pass.setForeground(new java.awt.Color(254, 255, 255));
        pass.setText("12345678");
        pass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pass.setCaretColor(new java.awt.Color(254, 255, 255));
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
        });
        jPanel5.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 371, 36));

        button1.setActionCommand("Sing in");
        button1.setBackground(new java.awt.Color(64, 64, 64));
        button1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Sign in");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        button1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button1KeyPressed(evt);
            }
        });
        jPanel5.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 370, 50));

        jLabel3.setBackground(new java.awt.Color(35, 43, 43));
        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 254));
        jLabel3.setText("Password");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 23));

        jLabel7.setBackground(new java.awt.Color(35, 43, 43));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        exitLable.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        exitLable.setForeground(new java.awt.Color(254, 255, 255));
        exitLable.setText("   X");
        exitLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLableMouseExited(evt);
            }
        });
        exitLable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exitLableKeyPressed(evt);
            }
        });
        jPanel5.add(exitLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 40, 30));

        bn_setupdata.setBackground(new java.awt.Color(64, 64, 65));
        bn_setupdata.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        bn_setupdata.setForeground(new java.awt.Color(255, 255, 254));
        bn_setupdata.setText("Set up database");
        bn_setupdata.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bn_setupdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bn_setupdataActionPerformed(evt);
            }
        });
        jPanel5.add(bn_setupdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 370, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 470, 540));

        jPanel4.setBackground(new java.awt.Color(62, 16, 136));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/3.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 40, 60));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/4.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 110, 80));

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 254));
        jLabel2.setText("Parking System");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 310, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        login();
    }//GEN-LAST:event_button1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed

    }//GEN-LAST:event_passActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        if (user.getText().equals("username")) {
            user.setText("");
        }
        if (pass.getText().equals("")) {
            pass.setText("12345678");
        }

    }//GEN-LAST:event_userFocusGained

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        if (pass.getText().equals("12345678")) {
            pass.setText("");
        }
        if (user.getText().equals("")) {
            user.setText("username");
        }


    }//GEN-LAST:event_passFocusGained

    private void exitLableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exitLableKeyPressed

    }//GEN-LAST:event_exitLableKeyPressed

    private void exitLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLableMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitLableMouseClicked

    private void exitLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLableMouseEntered
        exitLable.setForeground(Color.RED);
    }//GEN-LAST:event_exitLableMouseEntered

    private void exitLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLableMouseExited
        exitLable.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitLableMouseExited

    private void button1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button1KeyPressed

    }//GEN-LAST:event_button1KeyPressed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            login();
        }
    }//GEN-LAST:event_passKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void bn_setupdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bn_setupdataActionPerformed
        SetupDatabase se = new SetupDatabase();
	se.setLocationRelativeTo(null);
	se.setVisible(true);
    }//GEN-LAST:event_bn_setupdataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UiLogin ui = new UiLogin();
	ui.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bn_setupdata;
    private java.awt.Button button1;
    private javax.swing.JLabel exitLable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
